# .ls-lint.yml

ls:
    src:
        .dir: regex:[a-z0-9\-_]+
        .tsx: camelCase | PascalCase
        .test.tsx: camelCase | PascalCase
        .ts: camelCase
        .test.ts: camelCase
        .d.ts: kebab-case
        .css: kebab-case
        .scss: regex:[_a-z\-]+
        .module.scss: PascalCase
        .html: kebab-case
        .json: kebab-case
        .md: regex:[A-Z]+
        .lock: kebab-case
        .yml: kebab-case
        .svg: kebab-case
        .png: kebab-case
        .jpg: kebab-case
ignore:
    - node_modules
    - src/**/*/__snapshots__
